<?php
$lengths = array('teamname'=>50,
      'city'=>20,
      'studyplace'=>50,
      'address'=>50,
      'phone'=>13,
      'fax'=>13,
      'contactname'=>50,
      'contactphone'=>13,
      'contactmail'=>30,
      'headname'=>40,
      'headpost'=>30,
      'headpassportno'=>11,
      'headpassportplace'=>100,
      'headaddress'=>50,
      'headinn'=>13,
      'coachname'=>40,
      'coachpost'=>30,
      'coachpassportno'=>11,
      'coachpassportplace'=>100,
      'coachaddress'=>50,
      'coachinn'=>13,
      'contestant1name'=>40,
      'contestant1studyplace'=>50,
      'contestant1faculty'=>50,
      'contestant1classcourse'=>3,
      'contestant1passportno'=>11,
      'contestant1passportplace'=>100,
      'contestant1address'=>50,
      'contestant1inn'=>13,
      'contestant2name'=>40,
      'contestant2studyplace'=>50,
      'contestant2faculty'=>50,
      'contestant2classcourse'=>3,
      'contestant2passportno'=>11,
      'contestant2passportplace'=>100,
      'contestant2address'=>50,
      'contestant2inn'=>13,
      'contestant3name'=>40,
      'contestant3studyplace'=>50,
      'contestant3faculty'=>50,
      'contestant3classcourse'=>3,
      'contestant3passportno'=>11,
      'contestant3passportplace'=>100,
      'contestant3address'=>50,
      'contestant3inn'=>13,
      'password'=>20,
      'repeatpassword'=>20,
      'language'=>20);
$names = array('teamname'=>'название команды',
      'city'=>'город',
      'studyplace'=>'учебное заведение',
      'address'=>'адрес учебного заведени€',
      'phone'=>'телефон',
      'fax'=>'факс',
      'contactname'=>'контактное лицо',
      'contactphone'=>'контактный телефон',
      'contactmail'=>'контактный e-mail',
      'headname'=>'руководитель команды',
      'headpost'=>'руководитель команды - должность',
      'headpassportno'=>'руководитель команды - сери€ и номер паспорта',
      'headpassportplace'=>'руководитель команды - кем выдан паспорт',
      'headaddress'=>'руководитель команды - адрес',
      'headinn'=>'руководитель команды - »ЌЌ',
      'coachname'=>'тренер команды',
      'coachpost'=>'тренер команды - должность',
      'coachpassportno'=>'тренер команды - сери€ и номер паспорта',
      'coachpassportplace'=>'тренер команды - кем выдан паспорт',
      'coachaddress'=>'тренер команды - адрес',
      'coachinn'=>'тренер команды - »ЌЌ',
      'contestant1name'=>'первый участник',
      'contestant1studyplace'=>'первый участник - место учебы',
      'contestant1faculty'=>'первый участник - факультет',
      'contestant1classcourse'=>'первый участник - класс/курс',
      'contestant1passportno'=>'первый участник - сери€ и номер паспорта',
      'contestant1passportplace'=>'первый участник - кем выдан паспорт',
      'contestant1address'=>'первый участник - адрес',
      'contestant1inn'=>'первый участник - »ЌЌ',
      'contestant2name'=>'второй участник',
      'contestant2studyplace'=>'второй участник - место учебы',
      'contestant2faculty'=>'второй участник - факультет',
      'contestant2classcourse'=>'второй участник - класс/курс',
      'contestant2passportno'=>'второй участник - сери€ и номер паспорта',
      'contestant2passportplace'=>'второй участник - кем выдан паспорт',
      'contestant2address'=>'второй участник - адрес',
      'contestant2inn'=>'второй участник - »ЌЌ',
      'contestant3name'=>'третий участник',
      'contestant3studyplace'=>'третий участник - место учебы',
      'contestant3faculty'=>'третий участник - факультет',
      'contestant3classcourse'=>'третий участник - класс/курс',
      'contestant3passportno'=>'третий участник - сери€ и номер паспорта',
      'contestant3passportplace'=>'третий участник - кем выдан паспорт',
      'contestant3address'=>'третий участник - адрес',
      'contestant3inn'=>'третий участник - »ЌЌ',      
      'password'=>'пароль',
      'repeatpassword'=>'повтор парол€',
      'language'=>'€зык программировани€');
$fill = array('teamname',
      'city',
      'studyplace',
      'address',
      'phone',
      'fax',
      'contactname',
      'contactphone',
      'contactmail',
      'headname',
      'headpost',
      'headpassportno',
      'headpassportplace',
      'headaddress',
      'headinn',
      'coachname',
      'coachpost',
      'coachpassportno',
      'coachpassportplace',
      'coachaddress',
      'coachinn',
      'contestant1name',
      'contestant1studyplace',
      'contestant1classcourse',
      'contestant1passportno',
      'contestant1passportplace',
      'contestant1address',
      'contestant1inn',
      'contestant2name',
      'contestant2studyplace',
      'contestant2classcourse',
      'contestant2passportno',
      'contestant2passportplace',
      'contestant2address',
      'contestant2inn',
      'contestant3name',
      'contestant3studyplace',
      'contestant3classcourse',
      'contestant3passportno',
      'contestant3passportplace',
      'contestant3address',
      'contestant3inn',      
      'password',
      'repeatpassword',
      'language');
?>
